#!/usr/bin/env python3
"""
!!! Generated by Claude !!!
mp4_to_prime_png.py

Convert an MP4 video into the single horizontal "filmstrip" PNG expected
by the HP Prime dvidW() video player (DIMGROB_P / BLIT_P).

Each sampled frame is scaled + center-cropped to FRAME_W x FRAME_H
(default 320x240, the Prime's screen resolution) and the frames are
laid out left-to-right in one wide image:

    [frame0][frame1][frame2] ... [frameN-1]

dvidW() then walks across this strip 320px at a time, wrapping back to
the start when it runs out of frames.

Usage:
    python mp4_to_prime_png.py input.mp4 output.png
    python mp4_to_prime_png.py input.mp4 output.png --fps 25
    python mp4_to_prime_png.py input.mp4 output.png --fps 20 --max-width 20000
"""

import argparse
import sys

import cv2
import numpy as np
from PIL import Image


def fit_frame(frame, target_w, target_h):
    """Scale frame to cover target_w x target_h, then center-crop to it
    (preserves aspect ratio, no stretching/distortion)."""
    h, w = frame.shape[:2]
    scale = max(target_w / w, target_h / h)
    new_w, new_h = max(1, round(w * scale)), max(1, round(h * scale))
    resized = cv2.resize(frame, (new_w, new_h), interpolation=cv2.INTER_AREA)

    x0 = (new_w - target_w) // 2
    y0 = (new_h - target_h) // 2
    return resized[y0:y0 + target_h, x0:x0 + target_w]


def extract_frames(path, target_fps, frame_w, frame_h, max_frames):
    cap = cv2.VideoCapture(path)
    if not cap.isOpened():
        raise IOError(f"Could not open video file: {path}")

    src_fps = cap.get(cv2.CAP_PROP_FPS) or target_fps
    step = max(src_fps / target_fps, 1.0)  # source frames per output frame

    frames = []
    src_index = 0.0
    next_grab = 0.0

    while True:
        ok, frame = cap.read()
        if not ok:
            break

        if src_index >= next_grab:
            frame = fit_frame(frame, frame_w, frame_h)
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frames.append(frame)
            next_grab += step

            if max_frames is not None and len(frames) >= max_frames:
                break

        src_index += 1.0

    cap.release()
    return frames, src_fps


def build_filmstrip(frames, frame_w, frame_h):
    n = len(frames)
    strip = np.zeros((frame_h, frame_w * n, 3), dtype=np.uint8)
    for i, f in enumerate(frames):
        strip[:, i * frame_w:(i + 1) * frame_w] = f
    return strip


def main():
    parser = argparse.ArgumentParser(
        description="Convert an MP4 into an HP Prime dvidW()-compatible filmstrip PNG.")
    parser.add_argument("input", help="input .mp4 file")
    parser.add_argument("output", help="output .png filmstrip file")
    parser.add_argument("--fps", type=float, default=25.0,
                         help="frame rate to sample the video at (default: 25)")
    parser.add_argument("--frame-width", type=int, default=320,
                         help="width of each frame in pixels (default: 320)")
    parser.add_argument("--frame-height", type=int, default=240,
                         help="height of each frame in pixels (default: 240)")
    parser.add_argument("--max-width", type=int, default=30000,
                         help="max total filmstrip width in pixels, matching "
                              "the DIMGROB_P(G4,30000,240) size in dvidW() "
                              "(default: 30000)")
    args = parser.parse_args()

    max_frames = args.max_width // args.frame_width

    frames, src_fps = extract_frames(
        args.input, args.fps, args.frame_width, args.frame_height, max_frames
    )

    if not frames:
        sys.exit("No frames were extracted -- check the input file.")

    if len(frames) >= max_frames:
        print(f"Note: hit the {args.max_width}px width limit "
              f"({max_frames} frames) -- video was trimmed to fit.")

    strip = build_filmstrip(frames, args.frame_width, args.frame_height)
    Image.fromarray(strip, mode="RGB").save(args.output)

    duration = len(frames) / args.fps
    print(f"Wrote {args.output}")
    print(f"  {len(frames)} frames, {strip.shape[1]}x{strip.shape[0]}px")
    print(f"  ~{duration:.2f}s of playback at {args.fps} fps "
          f"(source was {src_fps:.2f} fps)")


if __name__ == "__main__":
    main()